[package]
name = "pro-audio-config"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk = { version = "0.15", features = ["v3_22"] }
gio = "0.15"
glib = "0.15"
dirs = "5.0"
async-channel = "2.0"
whoami = "1.0"

[dev-dependencies]
mockall = "0.11"
